// The 12 distinct situations, not the number of assertions or HTTP exchanges.
export const cases = [
  { id: 'TC01', title: 'Paginación válida y aislamiento', operation: 'GET /orders?page=1&limit=2 y page=2', risk: 'Omitir, duplicar o filtrar mal pedidos', pre: '3 pedidos A y 1 B de SETUP', data: 'page=1,2; limit=2; sesión A', expected: '200; páginas 2+1; total 3; ningún pedido B', assertions: 'Esquema OrderPage, metadatos, IDs completos sin solapamiento, propietario A', cleanup: 'Solo lectura; SETUP de siguiente ejecución reinicia' },
  { id: 'TC02', title: 'Página inválida', operation: 'GET /orders?page=0&limit=2', risk: 'Aceptar índice inválido', pre: 'Sesión A vigente', data: 'page=0; limit=2', expected: '400 VALIDATION_ERROR; sin listado', assertions: 'Estado, esquema de error y código específico', cleanup: 'Sin cambios' },
  { id: 'TC03', title: 'Crear pedido válido', operation: 'POST /orders', risk: 'Importe o propietario manipulable', pre: 'Sesión A; total inicial 3', data: 'product=CUADERNO; quantity=2', expected: '201; Q50; propietario A; draft; contador 0; total propio 4', assertions: 'Order, Location, UUID nuevo, precio, estado inicial; GET listado confirma efecto', cleanup: 'CLEANUP elimina createdId de esta corrida' },
  { id: 'TC04', title: 'Consultar creación persistida', operation: 'GET /orders/{createdId}', risk: 'Creación no persistida o incompatible con contrato', pre: 'TC03 guardó createdId actual', data: 'createdId; sesión A', expected: '200; mismo ID, cantidad 2, total numérico 50 y draft', assertions: 'Order, igualdad de valores y estado; detecta total convertido a string', cleanup: 'Solo lectura; CLEANUP elimina pedido' },
  { id: 'TC05', title: 'Cantidad inválida sin efecto', operation: 'POST /orders', risk: 'Pedido de cantidad cero', pre: 'TC03; total propio 4', data: 'product=CUADERNO; quantity=0', expected: '400 VALIDATION_ERROR; total sigue 4 y mismo conjunto de IDs', assertions: 'Error, código; GET posterior OrderPage y conjunto exacto de IDs', cleanup: 'Rechazo no debe crear datos; CLEANUP elimina pedido válido' },
  { id: 'TC06', title: 'Campo obligatorio ausente', operation: 'POST /orders', risk: 'Pedido incompleto o con valores por defecto', pre: 'TC03; total propio 4', data: 'product=CUADERNO sin quantity', expected: '400 VALIDATION_ERROR; ningún pedido adicional', assertions: 'Error, código; GET posterior total e IDs inalterados', cleanup: 'Sin nuevo recurso; CLEANUP elimina pedido válido' },
  { id: 'TC07', title: 'Sin credenciales', operation: 'GET /orders/{createdId}', risk: 'Exposición anónima de pedido protegido', pre: 'TC03; recurso real existente', data: 'Sin Authorization', expected: '401 UNAUTHORIZED; WWW-Authenticate Bearer; sin datos del pedido', assertions: 'Error estricto sin campos adicionales, código y desafío', cleanup: 'Sin cambios' },
  { id: 'TC08', title: 'Credencial inválida', operation: 'GET /orders/{createdId}', risk: 'Aceptar credencial no emitida', pre: 'TC03; recurso existente', data: 'Bearer invalid-demo-session (literal sin validez)', expected: '401 UNAUTHORIZED', assertions: 'Estado, Error estricto, código y WWW-Authenticate', cleanup: 'Sin cambios' },
  { id: 'TC09', title: 'Acceso y modificación de pedido ajeno', operation: 'GET y PUT /orders/{foreignId}/confirmation', risk: 'Lectura o confirmación horizontal no autorizada', pre: 'Pedido B draft generado por SETUP', data: 'foreignId; sesión A; comprobación final con sesión B', expected: '403 en GET y PUT; GET autorizado B conserva draft y contador 0', assertions: 'Errores FORBIDDEN; Order propio B; sin efecto de confirmación', cleanup: 'Sin modificaciones autorizadas; SETUP reinicia fixture' },
  { id: 'TC10', title: 'Recurso inexistente', operation: 'GET /orders/00000000-0000-4000-8000-000000000000', risk: 'Respuesta ambigua o recurso ficticio', pre: 'Sesión A; UUID reservado no generado por randomUUID', data: 'UUID v4 inexistente controlado', expected: '404 NOT_FOUND', assertions: 'Estado, Error estricto y código', cleanup: 'Sin cambios' },
  { id: 'TC11', title: 'Confirmar borrador y verificar cambio', operation: 'PUT /orders/{createdId}/confirmation y GET', risk: 'Cambio no aplicado o no persistido', pre: 'Pedido de TC03 en draft', data: 'Sin cuerpo; sesión A', expected: '200; confirmed; contador 1; fecha válida; GET confirma el cambio', assertions: 'Order, status, total, contador y fecha; lectura posterior coincide', cleanup: 'CLEANUP elimina pedido confirmado' },
  { id: 'TC12', title: 'Repetir confirmación: efecto final idempotente', operation: 'PUT /orders/{createdId}/confirmation y GET /orders/{id}, /orders', risk: 'Duplicar confirmación o crear otro pedido', pre: 'TC11 guarda confirmedAt y confirmación original', data: 'Mismo PUT sin cuerpo', expected: '200; contador persistido 1; misma fecha; Q50; total propio 4; mismos IDs', assertions: 'Order de respuesta y lectura posterior; OrderPage, contador, fecha, precio y conjunto exacto de IDs', cleanup: 'CLEANUP DELETE + GET 404 + listado vuelve a 3; borra variables temporales' }
];
